### PR TITLE
Implement support for the sourceMapIncludeSources option

### LINKED ISSUE #101: Implement sourceMapIncludeSources
See https://github.com/sass/sass/pull/3226
See https://github.com/sass/embedded-protocol/pull/87 adding the corresponding option in the version 1.0.0.beta.18 of the embedded-protocol and https://github.com/sass/dart-sass-embedded/pull/62 implementing it in the embedded compiler.

### PR DESCRIPTION
**Pull request by stof**
This also allows implement the sourceMapContents option of the legacy API.

Closes #101
https://github.com/sass/sass-spec/pull/1774
Depends on https://github.com/sass/dart-sass-embedded/pull/62

### CODE REVIEW

**Comment by stof** [comment]
@nex3 looks like https://github.com/sass/embedded-host-node/pull/104 does not work to use a PR of the embedded compiler

**Comment by stof** [comment]
@nex3 the bug is actually in `sass/clone-link-repo`, where it always skip the checkout when `default-ref` is null, even when a PR is found. I submitted https://github.com/sass/clone-linked-repo/pull/6 to fix that.

**Comment by stof** [comment]
And there was a second issue in the CI setup, fixed in #107 (and included temporarily in this PR as well, to be able to have a running CI build)

**Comment by nex3** [comment]
This now depends on https://github.com/sass/embedded-host-node/pull/108.

**Comment by nex3** [comment]
...and #110, because Yargs is an unfathomable beast.

**Review by nex3 — APPROVED** [review]

**Pull request merged**
